### ISSUE TITLE
1000 in function print-serial-plan in file solution-converter.lisp

### ISSUE THREAD

**Issue by lispm** [shop-planner/shop3#10]
just a wild guess, but this looks like the 1000 should be the variable internal-time-units-per-second . It looks like the code assumes that time units are always 1000. Are they?

Maybe ignore this issue, I would have to look at the PDDL definition first to make a useful comment. Sigh.

**Comment by rpgoldman** [comment]
I *think* that's ok (but it was written 17 years ago by someone else whom I have never met!).  The planner emits runtimes in seconds, and this seems to bump them to milliseconds.

There's not even any reason to believe that today's PDDL plan format is the same as it was in 2002.

This was just done to submit entries in IPC-2002.  It should be regarded as primarily of historical interest.  Maybe I should just remove it.
