### ISSUE TITLE
hand-steer in find-plans doesn't work with some task lists

### ISSUE THREAD

**Issue by ko56** [shop-planner/shop3#106]
If the the atoms in the problem file's task list contain `:task`, e.g.

`((:task add-to-KB) (:task create-service JF))`

then the `:hand-steer` in `(find-plans 'demo-net :hand-steer t)` has no effect.
If the `:task` is removed, things work as expected.

**Comment by rpgoldman** [comment]
Will you please post a MWE? If you do, I will have a look as soon as I can manage
