### ISSUE TITLE
License Type?

### ISSUE THREAD

**Issue by agundy** [shop-planner/shop3#11]
Hello! Awesome project, but without a license it is hard for others to determine how and where they can use the code. I just wondered what license is on this code, and if there is one and I missed it, it might be good to make it more prominent.

**Comment by rpgoldman** [comment]
It's Mozilla public license.  I will put this in the Defsystem metadata, and the README, but it's at the top of the`.asd` file.

**Comment by rpgoldman** [comment]
Readme and ASDF system definition updated in 33bb9c8175fff58b906796be1dae960c09607d8b

**Comment by agundy** [comment]
Thanks for the prompt response!
