### ISSUE TITLE
SBCL/Windows error, known bug

### ISSUE THREAD

**Issue by mason-bially** [shop-planner/shop3#12]
[There is a known bug in SBCL](https://bugs.launchpad.net/sbcl/+bug/1342005) that causes it to misbehave with CRLF line endings.

Specifically I get it here:

```
; file: C:/Machine/Toolchains/quicklisp/shop3/shop3/theorem-prover/theorem-prover.lisp
; in: DEFUN DO-CONJUNCT-FROM-AXIOM
;     (SHOP3.UNIFIER:TRACE-PRINT :AXIOMS SHOP3.THEOREM-PROVER::AX-BRANCH-NAME
;                                SHOP3.COMMON:STATE
;                                "~2%Level ~s, applying axiom ~s~%      goal ~s~
;                           ~%      tail ~s"
;                                SHOP3.THEOREM-PROVER::LEVEL
;                                SHOP3.THEOREM-PROVER::AX-BRANCH-NAME
;                                SHOP3.THEOREM-PROVER::GOAL1
;                                (SHOP3.UNIFIER:APPLY-SUBSTITUTION
;                                 SHOP3.THEOREM-PROVER::AX-BRANCH
;                                 SHOP3.THEOREM-PROVER::MGU1))
```

In this expansion:

```
; caught ERROR:
;   during macroexpansion of
;   (FORMATTER "~2%Level ~s, applying axiom ~s~%      goal ~s~
;                           ~%      tail ~s").
;   Use *BREAK-ON-SIGNALS* to intercept.
;
;    error in FORMAT: Unknown directive (character: Return)
;     ~2%Level ~s, applying axiom ~s~%      goal ~s~
;                           ~%      tail ~s
;                                                   ^

;     (SHOP3.UNIFIER:TRACE-PRINT :GOALS (CAR SHOP3.THEOREM-PROVER::GOAL1)
;                                SHOP3.COMMON:STATE
;                                "~2%Level ~s, axiom matches goal ~s~
;                       ~%     axiom ~s~%satisfiers ~s"
;                                SHOP3.THEOREM-PROVER::LEVEL
;                                SHOP3.THEOREM-PROVER::GOAL1
;                                SHOP3.THEOREM-PROVER::AX-BRANCH-NAME
;                                SHOP3.THEOREM-PROVER::MGU1)
; --> WHEN IF WHEN IF PROGN
```

I might consider forcing line endings on `.lisp` files to LF (my current solution), it may also be possible to avoid the error by avoiding multi-line format strings.

**Comment by rpgoldman** [comment]
I think it's something about your checkout that causes this, isn't it?  I.e., you just need to configure git to check it out without generating windows newlines. See this [stack exchange post](https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows)

**Comment by mason-bially** [comment]
Yes and that is how I fixed it, however it involves modifying the repo on an individual level for every windows user due to a bug in common lisp. My point is this is a repo level bug. The answer in the thread you linked even states the answer is to modify the `.gitattributes` file, so unless you commit it somewhere, every windows user with SBCL is going to have this problem and have to go through the much tricker next step of rechecking everything out.

**Comment by rpgoldman** [comment]
Can you tell me how to fix the `.gitattributes` file, and I will do so? I don't use windows, nor do I have access to a Windows machine.  Pull request would be optimal, but a description would do.

**Comment by mason-bially** [comment]
I would worry about being overzealous in my current solution (all text files). I'll see if I can refine it (just lisp files) and then PR it.

**Comment by rpgoldman** [comment]
Thanks.  I will pull it after that.
I agree that you should be worried -- who knows what it would do to the manual toolchain! 🤪

**Comment by rpgoldman** [comment]
Thanks! merged.
