### ISSUE TITLE
Removing nicknames and/or remove versions

### ISSUE THREAD

**Issue by guicho271828** [shop-planner/shop3#2]
If multiple versions of shop systems are expected to be loaded on a single lisp image, it does not make sense to add nicknames as the package names are global.

Given that this does not happen, the only reason for naming the packages with version numbers added seems to be maintaining the backward compatibility.
To keep the source code healthy, I would suggest renaming all package names `s/shop[23]/shop/g` .

There are also some packages that do not follow the hierarchical naming, separated by hyphens instead of dots.

**Comment by rpgoldman** [comment]
I didn't want to break backwards compatibility instantly.  I was thinking of removing the SHOP2 aliases in version 3.1, after which it *would* be possible to have two different versions of SHOP in the same image.

I found and fixed the naming inconsistencies (I think I got them all) in the process of making the first version of the SHOP3 manual.

**Comment by guicho271828** [comment]
I didn't suggest removing the nicknames. I suggested removing the version number from package names (i.e. `shop`, `shop.unifier`), but you can keep the nicknames with versions added (`shop2`, `shop2.unifier`).

Also, I believe **within this repository** all package names should point to the main package names, not the nicknames.
