### ISSUE TITLE
missing component: fiveam-asdf

### ISSUE THREAD

**Issue by pfpschneider** [shop-planner/shop3#24]
* (ql:quickload "shop3")
While evaluating the form starting at line 190, column 0
  of #P"/home/peter.patel/quicklisp/local-projects/shop3/shop3/shop3.asd":

debugger invoked on a MISSING-COMPONENT in thread #<THREAD "main thread" RUNNING {10005E85B3}>: Component "fiveam-asdf" not found

**Comment by rpgoldman** [comment]
We include this component in with the SHOP3 distribution.  To activate it you need to make sure that the git submodules are populated.
Getting them populated *might* be enough -- I'm not sure about how quicklisp searches.
If it's *not* enough, you should be able to take any of the libraries you need from `ext/` and make symbolic links (e.g., `ln -s /home/peter.patel/quicklisp/local-projects/shop3/jenkins/ext/fiveam-asdf /home/peter.patel/quicklisp/local-projects/`).
Please let me know if that does or does not work so that we can get you rolling and so that we can improve the installation instructions.
Also, I will try to get `fiveam-asdf` into Quicklisp; I have been meaning to for ages.

**Comment by pfpschneider** [comment]
Aah, so I didn't have submodules populated.  I don't think there was documentation about that.

I did get an error when cloning the submodules


git submodule update
Cloning into '/home/peter.patel/quicklisp/local-projects/shop3/jenkins/ext/alexandria'...
warning: redirecting to https://gitlab.common-lisp.net/alexandria/alexandria.git/
Cloning into '/home/peter.patel/quicklisp/local-projects/shop3/jenkins/ext/asdf-flv'...
Cloning into '/home/peter.patel/quicklisp/local-projects/shop3/jenkins/ext/fiveam'...
Cloning into '/home/peter.patel/quicklisp/local-projects/shop3/jenkins/ext/fiveam-asdf'...
Cloning into '/home/peter.patel/quicklisp/local-projects/shop3/jenkins/ext/iterate'...
Cloning into '/home/peter.patel/quicklisp/local-projects/shop3/jenkins/ext/pddl-tools'...
Cloning into '/home/peter.patel/quicklisp/local-projects/shop3/jenkins/ext/sb-texinfo'...
Cloning into '/home/peter.patel/quicklisp/local-projects/shop3/jenkins/ext/trivial-backtrace'...
Cloning into '/home/peter.patel/quicklisp/local-projects/shop3/jenkins/ext/trivial-garbage'...
Submodule path 'jenkins/ext/alexandria': checked out 'd44f543ca5c141aa13ec311056beca8a89fe9903'
Submodule path 'jenkins/ext/asdf-flv': checked out 'fc5b7399767ca35bfb420bbeb9e08494e441dc69'
Submodule path 'jenkins/ext/fiveam': checked out '5fa3ebb57273e43f01402d0a0764cc287179d1cc'
Submodule path 'jenkins/ext/fiveam-asdf': checked out '63227710c827b7ebb03bb9aa2bb9498ae23a371a'
Submodule path 'jenkins/ext/iterate': checked out 'a1c47b2b74f6c96149d717be90c07a1b273ced69'
Submodule path 'jenkins/ext/pddl-tools': checked out 'e1c2718ecf208fe5c56cdabb169fa7045658ef7c'
error: Server does not allow request for unadvertised object ee72b5137eb71fe02f2b9ac84256d6beb7283b98
Fetched in submodule path 'jenkins/ext/sb-texinfo', but it did not contain ee72b5137eb71fe02f2b9ac84256d6beb7283b98. Direct fetching of that commit failed.

But I can get shop started even with these problems.

**Comment by rpgoldman** [comment]
I *think* I have fixed the submodules.  Would you please pull an update from GitHub and then run `git submodule update`.  I believe that `sb-texinfo` and `pddl-tools` should work now, but I'm not sure what went wrong with those two, so it would be helpful to know whether you can get them now.
Thanks!

**Comment by pfpschneider** [comment]
Looks good now, thanks.

**Comment by rpgoldman** [comment]
Thanks for checking. I updated the README file to emphasize that the submodules need to be updated.
