### ISSUE TITLE
How to use relative directory pathname in SHOP3?

### ISSUE THREAD

**Issue by yding25** [shop-planner/shop3#32]
Hello,

I want to know how to use **the relative directory pathname** in SHOP3? 

To load an example, the command is 
_* (load "examples/toy/basic-example.lisp")_
However, SHOP3 will show an error that **it does not find a corresponding file.** 
Thus, to fix it, I need to use **an absolute directory path**.
I think using an absolute directory pathname is so tedious. 
So, could you give me a solution to use the relative directory pathname in SHOP3?

**Comment by rpgoldman** [comment]
@yding25 This is not a problem with SHOP3: `LOAD` is a function of the underlying Common Lisp Programming language.  To use `LOAD` properly, you need to look at the relevant Common Lisp documentation: `load` evaluates relative pathnames using the configuration variable `*default-pathname-defaults*`.

For more information, I suggest *Practical Common Lisp* or *Paradigms of AI Programming* for an introduction to the language.
