### ISSUE TITLE
What does the expansions and inferences in the stats of the plans mean?

### ISSUE THREAD

**Issue by KIlian42** [shop-planner/shop3#50]
Hi, I have a very last question: What does the expansions and inferences in the stats of the plans mean? I'm just curious about what that mean and I can't find anything about it in the the manual. Many Thanks.

Kilian

**Comment by rpgoldman** [comment]
The number of expansions is the number of times that a search node is popped off the queue of tasks to be accomplished. So for a search with no backtracking, that would be the number of nodes in the completed plan tree (leaves and internal nodes).  As there is more backtracking, the ratio of expansions to plan tree size will increase.

As for inferences, it is very much the same, but this is the number of propositions to be proved that are popped off the theorem prover's search stack in the course of proving all of the preconditions in the course of generating the plan.  I don't have a nice neat story about how to evaluate this number, though -- to see if there's a lot of search, you would have to know about how complex the preconditions in the plan library are to know whether the theorem-prover is getting lost.

**Comment by KIlian42** [comment]
Many belated thanks for your answers and help! They helped me a lot for my thesis :-)

**Comment by rpgoldman** [comment]
You are quite welcome, thanks!  If you feel like sharing, I'd love to see the thesis.

**Comment by KIlian42** [comment]
[Bachelorarbeit-Kilian-Kramer.pdf](https://github.com/shop-planner/shop3/files/6210408/Bachelorarbeit-Kilian-Kramer.pdf)

Sure, here is my bachelor thesis :-). Unfortunately it is written in german (did not had the time to translate it).

**Comment by KIlian42** [comment]
I also made a manual summary in german if this might be for interest for the community:

[SHOP3_manual_germany.pdf](https://github.com/shop-planner/shop3/files/6210543/SHOP3_manual_germany.pdf)
