### ISSUE TITLE
texinfo problem in building documentation

### ISSUE THREAD

**Issue by ko56** [shop-planner/shop3#54]
I am not a texinfo expert! I have texinfo 6.7, and when I try bulding the documentation, I get the following error:

[ko@wiley ~/build/shop3/shop3/docs]$ make pdf
$mkfile_path is [/usr/home/ko/build/shop3/shop3/docs/Makefile]
$current_dir is [/usr/home/ko/build/shop3/shop3/docs/]
$root_dir is [/usr/home/ko/build/shop3]
sbcl --no-userinit --eval '(require :asdf)' \

...

@xrdef{#loading-the-planner-snt}{}
@xrdef{Executing the Planner-title}{Executing the Planner}
@xrdef{Executing the Planner-snt}{Section@tie 3.2}
@xrdef{#executing-the-planner-title}{Executing the Planner}
@xrdef{#executing-the-planner-snt}{}
@xrdef{find-plans-title}{@code {FIND-PLANS}}
@xrdef{find-plans-snt}{Section@tie 3.2.1}
(/usr/home/ko/build/shop3/shop3/docs/include/fun-shop-find-plans.texinfo
/usr/home/ko/build/shop3/shop3/docs/include/fun-shop-find-plans.texinfo:1: Unde
fined control sequence.
@findex ->@fnindex 
                   
l.1 @findex
            find-plans
@xrdef{Function find-plans-title}{@code {FIND-PLANS}}

I cannot find the @fnindex command in the TeXInfo documentation.
Thank you for your help.

**Comment by rpgoldman** [comment]
I will try to have a look at this soon. Meanwhile, the manual is available from the front page on GitHub, on the GitHub io page.

**Comment by rpgoldman** [comment]
The command is documented here: https://www.gnu.org/software/texinfo/manual/texinfo/html_node/Predefined-Indices.html

Would you please send some more details? I’m interested in what exactly triggers this. It looks almost like something is trying to read one of the included Tex info files as a top-level file, but I can’t tell from what’s here.  Try attaching the full transcript.

**Comment by ko56** [comment]
Thanks for the pointer to the manual. 
I had already looked at TeXinfo's manual in my Emacs, and I had found the page you mention above, but there's no @fnindex there.  Unless the "n" is some convention in TeXInfo that means "no"?

Anyhow,  I'm attaching the full transcript.

**Comment by rpgoldman** [comment]
I'm afraid I don't see an attachment.

**Comment by ko56** [comment]
Sorry, do you see it now?

**Comment by rpgoldman** [comment]
Just checked: I have the same version of Texinfo:

```
$ texi2dvi --version
texi2dvi (GNU Texinfo 6.7)
```

I also did `info texinfo` and on the page for predefined indices, I see `@fnindex`:

```
Next: Indexing Commands,  Up: Indices

11.1 Predefined Indices
=======================

Texinfo provides six predefined indices.  Here are their nominal
meanings, abbreviations, and the corresponding index entry commands:

'cp'
     ('@cindex') Concept index, for general concepts.
'fn'
     ('@findex') Function index, for function and function-like names
     (such as entry points of libraries).
```

**Comment by rpgoldman** [comment]
I don't see a transcript yet. Did you name it as a `.txt` file? GitHub is fussy about what it will let you attach.

**Comment by ko56** [comment]
It seems that I don't know how to attach a file in github.   May I mail you
directly a .gz file?
Or reply to this email and attach the .gz file?

**Comment by ko56** [comment]
Yes, I have the same info page, and that's what I have been referring to.
But maybe I'm not reading it properly.  Is it saying that  'fn' is an
abbreviation for ***@***.***'?
And it doesn't explicitly mention @fnindex,  only @findex.

 Kostas

**Comment by rpgoldman** [comment]
@ko56 If you have a github account maybe just upload your transcript as a Gist and post a link here.

**Comment by ko56** [comment]
It looks like GitHub doesn't like my browser (PaleMoon).  Anyhow, here is the link

https://gist.github.com/ko56/79b387b9a694ad5a2547af2a8842d27c

**Comment by rpgoldman** [comment]
As suspected, it looks like somehow your copy of Texinfo does not like the included files that are generated from the code.

I’ll have a look and see what I have in mine, but if you would post `/usr/home/ko/build/shop3/shop3/docs/include/fun-shop-find-plans.texinfo` that might be helpful, since that’s where it is going wrong:

```
/usr/home/ko/build/shop3/shop3/docs/include/fun-shop-find-plans.texinfo:1: Unde
fined control sequence.
@findex ->@fnindex 
                   
l.1 @findex
            find-plans
@xrdef{Function find-plans-title}{@code {FIND-PLANS}}
@xrdef{Function find-plans-snt}{}
/usr/home/ko/build/shop3/shop3/docs/include/fun-shop-find-plans.texinfo:3: Miss
ing number, treated as zero.
<to be read again> 
                   \fnindfile 
\temp ->\write \fnindfile 
                          {\entry{find-plans}{\folio }{\code {find-plans}}}
\safewhatsit ... \else \vskip -\whatsitskip \fi #1
                                                  \ifx \lastskipmacro \zeros...

\dosubind ...dcsname }\safewhatsit \dosubindwrite 
                                                  }\fi 
\deffngeneral ... ->\dosubind {fn}{\code {#3}}{#1}
                                                  \defname {#2}{}{#3}\magica...

\printdefunline #1#2->\begingroup #1#2 \endheader 
                                                  \interlinepenalty = 10000 ...
l.3 ...ks state-type hand-steer leashed out-stream
                             
```

Line 2037

I’ll see if there is something obvious I can find, but if there isn’t you may have to ask in a Texinfo forum.

I note also that there seem to be some problems with your SBCL/ASDF installation:

```
;; loading #P"/usr/local/lib/sbcl/asdf/asdf.lisp"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-aclrepl - picking #P"/usr/local/lib/sbcl/contrib/sb-aclrepl.asd" over #P"/usr/local/lib/sbcl/sb-aclrepl/sb-aclrepl.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-bsd-sockets - picking #P"/usr/local/lib/sbcl/contrib/sb-bsd-sockets.asd" over #P"/usr/local/lib/sbcl/sb-bsd-sockets/sb-bsd-sockets.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-cltl2 - picking #P"/usr/local/lib/sbcl/contrib/sb-cltl2.asd" over #P"/usr/local/lib/sbcl/sb-cltl2/sb-cltl2.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-concurrency - picking #P"/usr/local/lib/sbcl/contrib/sb-concurrency.asd" over #P"/usr/local/lib/sbcl/sb-concurrency/sb-concurrency.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-cover - picking #P"/usr/local/lib/sbcl/contrib/sb-cover.asd" over #P"/usr/local/lib/sbcl/sb-cover/sb-cover.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-executable - picking #P"/usr/local/lib/sbcl/contrib/sb-executable.asd" over #P"/usr/local/lib/sbcl/sb-executable/sb-executable.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-gmp - picking #P"/usr/local/lib/sbcl/contrib/sb-gmp.asd" over #P"/usr/local/lib/sbcl/sb-gmp/sb-gmp.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-grovel - picking #P"/usr/local/lib/sbcl/contrib/sb-grovel.asd" over #P"/usr/local/lib/sbcl/sb-grovel/sb-grovel.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-introspect - picking #P"/usr/local/lib/sbcl/contrib/sb-introspect.asd" over #P"/usr/local/lib/sbcl/sb-introspect/sb-introspect.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-md5 - picking #P"/usr/local/lib/sbcl/contrib/sb-md5.asd" over #P"/usr/local/lib/sbcl/sb-md5/sb-md5.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-mpfr - picking #P"/usr/local/lib/sbcl/contrib/sb-mpfr.asd" over #P"/usr/local/lib/sbcl/sb-mpfr/sb-mpfr.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-posix - picking #P"/usr/local/lib/sbcl/contrib/sb-posix.asd" over #P"/usr/local/lib/sbcl/sb-posix/sb-posix.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-queue - picking #P"/usr/local/lib/sbcl/contrib/sb-queue.asd" over #P"/usr/local/lib/sbcl/sb-queue/sb-queue.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-rotate-byte - picking #P"/usr/local/lib/sbcl/contrib/sb-rotate-byte.asd" over #P"/usr/local/lib/sbcl/sb-rotate-byte/sb-rotate-byte.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-rt - picking #P"/usr/local/lib/sbcl/contrib/sb-rt.asd" over #P"/usr/local/lib/sbcl/sb-rt/sb-rt.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-simple-streams - picking #P"/usr/local/lib/sbcl/contrib/sb-simple-streams.asd" over #P"/usr/local/lib/sbcl/sb-simple-streams/sb-simple-streams.asd"
WARNING:
   In source-registry entry /usr/local/lib/sbcl// found several entries for sb-sprof - picking #P"/usr/local/lib/sbcl/contrib/sb-sprof.asd" over #P"/usr/local/lib/sbcl/sb-sprof/sb-sprof.asd"
WARNING:
   You are using ASDF version 3.3.1 (probably from (require "asdf") or loaded
   by quicklisp) and have an older version of ASDF (and older than 2.27 at
   that) registered at #P"/usr/local/lib/common-lisp/asdf/asdf.asd". Having an
   ASDF installed and registered is the normal way of configuring ASDF to
   upgrade itself, and having an old version registered is a configuration
   error. ASDF will ignore this configured system rather than downgrade itself.
   In the future, you may want to either: (a) upgrade this configured ASDF to a
   newer version, (b) install a newer ASDF and register it in front of the
   former in your configuration, or (c) uninstall or unregister this and any
   other old version of ASDF from your configuration. Note that the older ASDF
   might be registered implicitly through configuration inherited from your
   system installation, in which case you might have to specify
   :ignore-inherited-configuration in your in your
   ~/.config/common-lisp/source-registry.conf or other source-registry
   configuration file, environment variable or lisp parameter. Indeed, a likely
   offender is an obsolete version of the cl-asdf debian or ubuntu package,
   that you might want to upgrade (if a recent enough version is available) or
   else remove altogether (since most implementations ship with a recent asdf);
   if you lack the system administration rights to upgrade or remove this
   package, then you might indeed want to either install and register a more
   recent version, or use :ignore-inherited-configuration to avoid registering
   the old one. Please consult ASDF documentation and/or experts.
```

**Comment by ko56** [comment]
I searched all files in /usr/home/ko/build/shop3/shop3/docs/include for 'fnindex', no match.
The line
@findex ->@fnindex 
makes me think that there is some .tex file somewhere that maps @findex to @fnindex.

The asdf issue has something to do with the sbcl package (this is FreeBSD) and the separate cl-asdf package.

Neither of these two issues seem worth pursuing farther right now.  Let me try building the planner and see how that goes.

**Comment by rpgoldman** [comment]
That sounds good.  I would kill the `cl-asdf` package -- I don't believe it's updated any more (I'm lead maintainer on ASDF, too).  If you really need an updated ASDF, you can pull it from common-lisp.net (just google for ASDF project) and put it in your user space -- you don't need it installed system wide.

And, as I said, you can read the whole manual on line.  If I can figure out how, I will make it downloadable from GitHub in PDF format, too.
