### ISSUE TITLE
updates to manual

### ISSUE THREAD

**Issue by ko56** [shop-planner/shop3#70]
@rpgoldman would you please look at the Discussion on suggested updates to the manual?  I've made lots of updates. (Then please close this issue.)

**Comment by ko56** [comment]
OK.  I have also sent you private email, as we discussed a while ago, but apparently it went into your spam.

**Comment by rpgoldman** [comment]
It's possible that happened, but also possible that I missed it: I have not had time to work on SHOP for the past 2-3 weeks. But you should see the new PR #71 now.
