### ISSUE TITLE
What IS shop3?

### ISSUE THREAD

**Issue by JMC-design** [shop-planner/shop3#75]
Have you noticed that nowhere in your readme does it actually mention what this program is or what it does? I have no idea why I'm looking at this.

**Comment by rpgoldman** [comment]
SHOP3 is a planner.  Specifically, it's a hierarchical task network (HTN) Artificial Intelligence (AI) planner.

Probably either that tells you what you need to know or tells you that you don't care! 😉

I added that to the README.

**Comment by JMC-design** [comment]
Thanks, that makes sense as to what it was doing in my open tabs.
