### ISSUE TITLE
More changes/fixes to manual

### ISSUE THREAD

**Issue by ko56** [shop-planner/shop3#76]
I'm attaching the latest manual.patch.gz.   Besides the typographical and other minor fixes, I've reorganized sec. 11.

In sec. 11.1, item 1, I think something more may need to be said about satisfiers/unifiers in axioms, concerning variables that don't appear in the head, but I don't know how to say it.

My opinion is that this section should precede the current sec. 10.

[manual.patch.gz](https://github.com/shop-planner/shop3/files/6885274/manual.patch.gz)

**Comment by rpgoldman** [comment]
Thanks for this. I am working to apply it.  But... how did you create it?

When I try applying it with `patch`, it does not have the expected format:

```
 $ patch < manual.patch
can't find file to patch at input line 5
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/shop3/docs/manual.texinfo b/shop3/docs/manual.texinfo
|index 7bf5b2e..5e514a9 100644
|--- a/shop3/docs/manual.texinfo
|+++ b/shop3/docs/manual.texinfo
--------------------------
```

So I tried 

```
~/lisp/shop $ git am manual.patch
Patch format detection failed.
```

But that does not work, either.

It looks like you are using `git diff` in which case, it would be better if you would either:

1. Use ordinary `diff` so I get a patch I can apply with `patch`
2. Use `git format-patch` to give something I can apply with `git am` or
3. Just use a GitHub pull request.

For now I was able to apply this patch, but only manually.  And you don't get credit for it the way you would with method 2 or 3, above.

**Comment by ko56** [comment]
I created the patch following the 2nd method in your old email below.
All the other patches I've sent were created the same way.

**Comment by ko56** [comment]
Sorry, I see I didn't append the right email, somehow.  Here is the correct text:

```
If you have committed these into your git repository, you can send me a patch using git format-patch. Here's a tutorial explaining how to do that:

https://www.git-tower.com/learn/git/faq/create-and-apply-patch/

That would be the best way, as in the easiest for me to apply.

Otherwise, if you haven't used git at all and haven't committed any of your changes, you could use

git diff master -- doc/manual.texinfo > manual.patch
That would give you a patch file that you could send to me, and that I could apply to the manual. (Note that I didn't check that command to make sure it has the right pathname to the manual.)

```

**Comment by rpgoldman** [comment]
@ko56 Did not mean to seem critical. It's just that if you continue to contribute -- and I hope you do! -- it would be easier if you did it in the standard way.

But if this is what works best for you, I will continue to take patch files.

**Comment by rpgoldman** [comment]
@ko56 

> My opinion is that this section should precede the current sec. 10.

So you mean swap sections 11 (General Notes on Shop3) and section 10 (Internal Technical Information) so that what is now 11 becomes 10?

Just want to be sure I understand what you have in mind.

**Comment by ko56** [comment]
Ok, I will try the github way to submit patches, although I d find github painful.
I will submit a test patch, and you'll let me know how it worked.

Concerning sec. 11, my opinion is that additional explanatory notes that mostly concern the usage of the tool should precede Internal Tech Info. So I would say swap the two sections.  Unless yoy have another idea.

**Comment by rpgoldman** [comment]
I am happy to make this change; just wanted to confirm it was what you suggested.

**Comment by ko56** [comment]
I am still struggling with git. I have a directory "shop3" which contains the master branch:
```
[ko@wiley ~/build]$ l shop3
img/		jenkins/	README.md	shop3/
[ko@wiley ~/build]$ 
```
I also have a directory "shop3-manual-fixes":
```
[ko@wiley ~/build]$ l shop3-manual-fixes
shop3/
[ko@wiley ~/build]$ l shop3-manual-fixes/shop3/
img/		jenkins/	README.md	shop3/
[ko@wiley ~/build]$ 
```
I created `shop3-manual-fixes` because git wouldn't let me check out the manual-fixes branch under ~/build. It said that the name "shop3" was already existing.

Anyhow, now I have some new changes in `~/build/shop3-manual-fixes/shop3/shop3/docs`.
What do I do to create a patch to send you?

**Comment by ko56** [comment]
I created the branch by 
```
[ko@wiley ~/build]$ cd shop3-manual-fixes
[ko@wiley ~/build/shop3-manual-fixes]$ git clone -b manual-fixes https://github.com/shop-planner/shop3.git
...
[ko@wiley ~/build/shop3-manual-fixes]$ 
```
Maybe I should have cd'd to `~/build/shop3` and created the branch there?
If so, I can easily go back and do this.

**Comment by rpgoldman** [comment]
I see what you did wrong. To make a branch you should just have done

    git checkout -b manual-fixes

You don't re-clone to make a branch.

When you do `git checkout` it does not matter what directory you are in (well, except you should _not_ be in one of the submodules below `jenkins`).

You ended up with an entirely new copy of the repository instead of a branch in the repo.

**Comment by ko56** [comment]
I think I finally have some sucess!  I re-did the creation of the branch, etc, and finally did

`git diff -p master manual-fixes > man.patch`

I attach the file.  Let me know if it makes sense, I hope so.
[man.patch.gz](https://github.com/shop-planner/shop3/files/6978990/man.patch.gz)

**Comment by rpgoldman** [comment]
What's gone wrong there is that `git` is interpreting the URL you gave it as the identifier for a thing like a branch that you are trying to fetch, and it can't parse it.

All you need is `git fetch origin` : that will fetch all the contents of `origin`, but will *not* merge `origin/manual-fixes` into your local copy of `manual-fixes`.  And that's what you want, because after that, you can do `git diff origin/manual-fixes manual-fixes` and see what changes are only in your local `manual-fixes`.

Meanwhile, I will see if the diffs I have are enough to make it possible for me to apply your patch.

**Comment by ko56** [comment]
OK, I did it.  Please try the attached man.patch.gz.
[man.patch.gz](https://github.com/shop-planner/shop3/files/7069757/man.patch.gz)

**Comment by ko56** [comment]
OK, I did it.  Hopefully correctly. See attached.
[man.diff.gz](https://github.com/shop-planner/shop3/files/7069764/man.diff.gz)
