### ISSUE TITLE
eq vs. eql

### ISSUE THREAD

**Issue by lispm** [shop-planner/shop3#9]
I see this in unify.lisp

    (eq (aref (symbol-name sym) 1) #\_)

Generally EQ is not defined for character values and also not for numeric values. EQ compares only for pointer equality. Primitive objects like characters, fixnums, some floats, ... could have copies.

Probably a good idea to replace EQ when comparing with characters and numbers with EQL for portability.

see also one EQ with a character in output.lisp, but there might be more where EQ does not directly gets used with a character object or numbers.

**Comment by rpgoldman** [comment]
This is fixed on my machine, and I am running the tests now.  If they pass, I will push the fix.

**Comment by rpgoldman** [comment]
Fixed in e97c702bc24ba1c53fb38233887bff549b8248ea
