### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [shop-planner/shop3#92]
Building with SBCL 2.1.10.195-bca540cd6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 4451658f34a6350cfad290f6a1826500efb66329

*openstacks-problem-translator* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BFC103}>: Component :SHOP2 not found, required by #<SYSTEM "openstacks-problem-translator">

```

*rovers-problem-translator* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BFC103}>: Component :SHOP2 not found, required by #<SYSTEM "rovers-problem-translator">

```

*shop3-thmpr-api* fails to build because of a failure in  _shop3_.

*shop3* fails to build with the following error:

```
; caught ERROR:
;   READ error during COMPILE-FILE: Package PLAN-TREE does not exist. Line: 106, Column: 37, File-Position: 2192 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/shop3/72c8dde5d3c1fa770f88d8adc3bccd931c0929bd/shop3-20211124-git/shop3/explicit-stack-search/decls.lisp" {1006D91B23}>
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BFC103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "shop3" "explicit-stack-search" "decls">

```

*shop3/openstacks* fails to build because of a failure in  _shop3_.

*shop3/pddl-helpers* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BFC103}>: Component "pddl-utils" not found, required by #<SYSTEM "shop3/pddl-helpers">

```

*shop3/plan-grapher* fails to build because of a failure in  _shop3_.

*shop3/rovers* fails to build because of a failure in  _shop3_.

*shop3/test-satellite* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BFC103}>: Component "pddl-utils" not found, required by #<SHOP-FIVEAM-TESTER "shop3/test-satellite">

```

*shop3/test* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BFC103}>: Component "pddl-utils" not found, required by #<SYSTEM "shop3/pddl-helpers">

```

*translate-satellite-problems* fails to build with the following error:

```
Unhandled ASDF/FIND-COMPONENT:MISSING-DEPENDENCY in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BFC103}>: Component :SHOP2/PDDL-HELPERS not found, required by #<SYSTEM "translate-satellite-problems">

```

[Full log here](http://report.quicklisp.org/2021-11-24/failure-report/shop3.html)

**Comment by rpgoldman** [comment]
Thanks for letting me know!  Obviously there is something terribly wrong with the way I have set up the GitHub CI for this project!

Fixing it this morning.

**Comment by rpgoldman** [comment]
I believe this is fixed now, @quicklisp 

Please reopen this issue if you still see errors in the Quicklisp build, and thanks for the report!
